name: "🚀 Feature Request"
description: "Request a new feature or enhancement."
title: "[FEAT]: ✨ "
labels: "enhancement"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "Provide a detailed description of the feature request."
    placeholder: "Describe the feature, its purpose, and how it would improve the application."
  validations:
    required: true
- type: textarea
  id: tasks
  attributes:
    label: "Tasks"
    description: "List all the necessary tasks required to implement this feature."
    value: |
      1. 
  validations:
    required: true
- type: textarea
  id: considerations
  attributes:
    label: "Considerations"
    description: "List any factors to keep in mind when implementing this feature."
    placeholder: |
      - Ensure consistency with the existing design.
      - Optimize performance and efficiency.
      - Test across different browsers and devices.
- type: textarea
  id: additional-notes
  attributes:
    label: "Additional Notes"
    description: "Any extra context, references, or related issues."
    placeholder: "Add links, design references, or any other relevant information."
